# Generated by Django 4.2.7 on 2025-01-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in days'),
        ),
    ]
